In [2]:
!pip list

Package                       Version
----------------------------- --------------------
absl-py                       1.4.0
aiohttp                       3.8.3
aiosignal                     1.2.0
alabaster                     0.7.12
amqp                          5.1.1
anaconda-client               1.11.0
anaconda-navigator            2.3.2
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
arviz                         0.11.2
asgiref                       3.6.0
astor                         0.8.1
astroid                       2.11.7
astropy                       5.1
astunparse                    1.6.3
async-timeout                 4.0.2
atomicwrites                  1.4.0
attrs                         21.4.0
auto-labeling-pipeline        0.1.21
Automat                       20.2.0
autopep8                      1.6.0
Bab

In [3]:
#!pip install -U tensorflow==2.0

In [4]:
import tensorflow as tf    # importing tensorflow libraries

In [5]:
tf.__version__

'2.9.1'

# Creating tensors through constants

In [6]:
hello = tf.constant("Hello Rahul Bhai!!")  
print(hello.numpy())                


b'Hello Rahul Bhai!!'


 # Creating tensors through operations

In [7]:
# creating nodes in computation graph 
node1 = tf.constant(33, dtype=tf.int32)   # creates a data node 
node2 = tf.constant(201, dtype=tf.int32)   # creates a data node
node3 = tf.add(node1, node2)             # creates a function node


# evaluating node3 and printing the result 
print("Sum of node1 and node2 is:",node3.numpy()) 


Sum of node1 and node2 is: 234


In [8]:
A  = tf.Variable(initial_value = ([[10,11,21,3],[55,26,7,8]]), shape=(2,4) , dtype = 'int32', name = 'A' )
print(A.numpy())
print(A.shape)
print(tf.rank(A))

[[10 11 21  3]
 [55 26  7  8]]
(2, 4)
tf.Tensor(2, shape=(), dtype=int32)


In [9]:
b = tf.Variable([[11],[2],[13],[4]])
print(b.shape)
print(tf.rank(b))

(4, 1)
tf.Tensor(2, shape=(), dtype=int32)


In [10]:
C = tf.Variable([[13,32],[36,43]])
print(C.shape)
print(tf.rank(C))
print(C)

(2, 2)
tf.Tensor(2, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[13, 32],
       [36, 43]])>


In [11]:
D = tf.constant(505, shape=[6,2])
print("rank of D :", tf.rank(D))
print("shape of D :" , D.shape)
print("content of D :",  D)

rank of D : tf.Tensor(2, shape=(), dtype=int32)
shape of D : (6, 2)
content of D : tf.Tensor(
[[505 505]
 [505 505]
 [505 505]
 [505 505]
 [505 505]
 [505 505]], shape=(6, 2), dtype=int32)


# Creating tensors from Existing Objects

In [12]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)   #converting a scalar value (5.0) into a tensor of rank 0 

In [13]:
print(tf.rank(tf_t))
print(tf.shape(tf_t))   # pl. note, the number after Rank_ and Shape_ are internal indices. 

print(tf.rank(tf_t))    #Note: if we do not use tfs.run(), the tf.rank will only describe the node
print(tf.shape(tf_t) )  # pl. note, the number after Rank_ and Shape_ are internal indices. 

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)


# Creating tensors from an array

In [14]:
import numpy as np

one_dim_array = ([13], [92], [38], [48], [52])
print("one_dim_array Shape : ", one_dim_array)

tf_t = tf.convert_to_tensor(one_dim_array, dtype=tf.float64)
print('\n')
print(tf_t)
print('rank of tf_t : ', tf.rank(tf_t))     #Note: if we do not use tfs.run(), the tf.rank will only describe the node
print('shape of tf_t: ', tf.shape(tf_t))
print('\n')
print('tf_t[0] : ', tf_t[0])
print('tf_t[0] : ', tf_t[2])
print('\n')
print('run(tf_t) : \n', tf_t)

one_dim_array Shape :  ([13], [92], [38], [48], [52])


tf.Tensor(
[[13.]
 [92.]
 [38.]
 [48.]
 [52.]], shape=(5, 1), dtype=float64)
rank of tf_t :  tf.Tensor(2, shape=(), dtype=int32)
shape of tf_t:  tf.Tensor([5 1], shape=(2,), dtype=int32)


tf_t[0] :  tf.Tensor([13.], shape=(1,), dtype=float64)
tf_t[0] :  tf.Tensor([38.], shape=(1,), dtype=float64)


run(tf_t) : 
 tf.Tensor(
[[13.]
 [92.]
 [38.]
 [48.]
 [52.]], shape=(5, 1), dtype=float64)


# Define tensorflow variables 

In [15]:
# Assume Linear Model y = w * x + b
# Define model parameters
w = tf.Variable([.23], tf.float32)
b = tf.Variable([-.43], tf.float32)


# Define model input and output
x = tf.Variable([5.0],tf.float32)
y = w * x + b

print("w:", w)
print("x:", x)
print("b:", b)
print("y:", y)



w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.23], dtype=float32)>
x: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([5.], dtype=float32)>
b: <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.43], dtype=float32)>
y: tf.Tensor([0.71999997], shape=(1,), dtype=float32)


# Linear model in tensorflow

In [16]:
train_X = [3.3, 4.4, 5.5, 6.71, 6.93, 4.168, 9.779, 6.182, 7.59, 2.167,
           7.042, 10.791, 5.313, 7.997, 5.654, 9.27, 3.1]
train_Y = [1.7, 2.76, 2.09, 3.19, 1.694, 1.573, 3.366, 2.596, 2.53, 1.221,
           2.827, 3.465, 1.65, 2.904, 2.42, 2.94, 1.3]
NUM_EXAMPLES = len(train_X)


#create model paramters with initial values 
W = tf.Variable(0.)
b = tf.Variable(0.)

#training info
train_steps = 100
learning_rate = 0.01

for i in range(train_steps):
  
  #watch the gradient flow 
  with tf.GradientTape() as tape:
    
    #forward pass 
    yhat = train_X * W + b
    
    #calcuate the loss (difference squared error)
    error = yhat - train_Y
    loss = tf.reduce_mean(tf.square(error))
  
  #evalute the gradient with the respect to the paramters
  dW, db = tape.gradient(loss, [W, b])

  #update the paramters using Gradient Descent  
  W.assign_sub(dW * learning_rate)
  b.assign_sub(db* learning_rate)

  #print the loss every 20 iterations 
  if i % 20 == 0:
    print("Loss at step {:03d}: {:.3f}".format(i, loss))
      
print(f'W : {W.numpy()} , b  = {b.numpy()} ')

Loss at step 000: 6.100
Loss at step 020: 0.217
Loss at step 040: 0.211
Loss at step 060: 0.206
Loss at step 080: 0.201
W : 0.3344224691390991 , b  = 0.2118747979402542 


In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
# Graphic display
plt.plot(train_X, train_Y, 'ro', label='Original data')
plt.plot(train_X, np.array(W * train_X + b), label='Fitted line')
plt.legend()
plt.show()

In [ ]:
def linear_model(X_val):
  print((W*X_val + b).numpy())

In [ ]:
linear_model(8)